add check pipenv for linux
OpenMined/PyDP pull request #160
Opened 2020-05-30 07:47 UTC by systemshift

# Pull Request

## Description
Please include a summary of the change and which issue is fixed. If this closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Affected Dependencies
List any dependencies that are required for this change.

## Type of Change
Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation (non-breaking change which adds documentation)
- [ ] Improvement (non-breaking change that improves the performance or reliability of existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I did follow the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md)
- [ ] I did follow the [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have added tests for my changes

## Additional Context
Please also include relevant motivation and context.

2020-05-30 17:38 UTC, chinmayshah99 approved these changes

2020-05-30 17:41 UTC, chinmayshah99 requested changes

2020-05-30 17:41 UTC, chinmayshah99 commented on prereqs_linux.sh
> +if python -c "import pipenv" &> /dev/null; then
In Linux systems with ubuntu, both python 2 and 3 are installed. 
`python` usually resolute to python2 and python3  is for python 3. 
We need to check which python version are we checking and then accordingly install it using pip

2020-05-30 17:41 UTC, chinmayshah99 commented on prereqs_linux.sh
> +    pip install pipenv
Same applies for choosing between pip and pip3.

2020-05-30 21:44 UTC, chinmayshah99 commented on prereqs_linux.sh
> +if python3 -c "import pipenv" &> /dev/null; then
If you just have python3 installed, does this work?
I suspect the env variable will be just `python` variable, and maybe `python3 `variable will be absent. 
Not sure, needs to be investigated. @replomancer thoughts?

2020-06-11 11:46 UTC, chinmayshah99 requested changes

2020-06-11 11:46 UTC, chinmayshah99 commented on prereqs_linux.sh
> +if command python --version | grep -q 'Python 3'; then
This should be added as another condition check ( else if condition)

2020-06-11 11:55 UTC, chinmayshah99 approved these changes

2020-06-12 01:37 UTC, codeboy5 approved these changes

2020-06-16 05:21 UTC, chinmayshah99 approved these changes

2020-06-16 05:21 UTC, merged