Introduce Python and C++ code coverage reports and checks
OpenMined/PyDP pull request #262
Opened 2020-08-21 15:49 UTC by alejandrosame

## Description
This PR implements #256 and #257. The current minimum coverage requirement for the CI check is 80%, which is specified by the `MIN_COVERAGE` variable inside `.env` file. The Makefile has the following new actions:
-  `check-coverage-python`: ensures that Python code coverage is at least `MIN_COVERAGE`%. Automatically called by `make test`.
-  `check-coverage-cpp`: ensures that C++ code coverage is at least `MIN_COVERAGE`%. Automatically called by `make test`.
-  `show-coverage`: collects coverage data generated during test execution and opens its report on a browser tab [see image below].
![cov_html_report](https://user-images.githubusercontent.com/1078000/90930507-a8b13d00-e3f2-11ea-8180-7cdca8a8b016.png)

## Affected Dependencies
Added the following python dependencies:
-  `coverage` to generate Python coverage reports.
-  `gcovr` to generate C++ coverage reports. 

## How has this been tested?
- `make test` executed succesfully
- CI changes tested in a [test PR](https://github.com/alejandrosame/PyDP/pull/4).

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2020-08-21 20:01 UTC, chinmayshah99 requested changes

2020-08-21 20:01 UTC, chinmayshah99 commented on .github/workflows/tests.yml
> +    - name: Check code coverage tests
split these into two separate name

2020-08-21 20:09 UTC, alejandrosame commented on .github/workflows/tests.yml
> +    - name: Check code coverage tests
Done on latest commit

2020-08-22 13:46 UTC, chinmayshah99 approved these changes

2020-08-22 13:46 UTC, merged