Added Serialize and Merge function
OpenMined/PyDP pull request #266
Opened 2020-08-22 21:05 UTC by chinmayshah99

## Description
With this serialize and merge function we cab enable distributed-federated computing

## How has this been tested?
- make tests passes

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2020-08-22 22:12 UTC, alejandrosame requested changes
I would clean up the comment and fix the typo to merge it cleanly. 

The other comment I made is more of a style remark. Since I'm not aware of any performance difference, I don't consider it a big deal of a change to make.

2020-08-22 22:12 UTC, alejandrosame commented on pydp/algorithms/_algorithm.py
>      # TODO: Wrap Summary class before exposing serialize and merge methods.
This comment can be deleted.

2020-08-22 22:12 UTC, alejandrosame commented on src/bindings/PyDP/pydp_lib/algorithm_builder.hpp
> +    pyself.def("serialize", [](Algorithm& pythis) { return pythis.Serialize(); });
Is this change required? Since we are just calling the function directly inside the lambda, I would leave the previous version for consistent style.

2020-08-22 22:12 UTC, alejandrosame commented on tests/algorithms/test_bounded_mean.py
> +def test_serialze_merge():
Typo: `test_serialze_merge` -> `test_serialize_merge`

2020-08-22 22:27 UTC, chinmayshah99 commented on src/bindings/PyDP/pydp_lib/algorithm_builder.hpp
> +    pyself.def("serialize", [](Algorithm& pythis) { return pythis.Serialize(); });
oh this was due to earlier change. Making this change. Thanks for the notice!

2020-08-22 22:43 UTC, alejandrosame commented on src/bindings/PyDP/pydp_lib/algorithm_builder.hpp
>      pyself.def("merge",
I think it applies the same than with `serialize`. Sorry for not being explicit on the first comment!

2020-08-22 23:05 UTC, chinmayshah99 commented on src/bindings/PyDP/pydp_lib/algorithm_builder.hpp
>      pyself.def("merge",
No worries, even I missed it.

2020-08-23 08:23 UTC, alejandrosame approved these changes
LGTM!

2020-08-23 18:56 UTC, merged