added introduction blog documentation
OpenMined/PyDP pull request #274
Opened 2020-08-27 03:55 UTC by shivaylamba

## Description
Converted the article (https://docs.google.com/document/d/17DseJokINbxJbBTBMJursrnUcvv_pgOeDQDtVTDHGpU/edit) written by @TravellerOnCode  into rst format to be added to the docs. 
Please review @chinmayshah99 

## Affected Dependencies
NA

## How has this been tested?
Tested by running on online rst viewers and editors. 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2020-08-27 06:01 UTC, chinmayshah99 approved these changes, later dismissed

2020-08-27 10:20 UTC, midopooler approved these changes, later dismissed
LGTM

2020-08-27 11:39 UTC, TravellerOnCode commented
Suggested Changes:
* Centre Align all images
* Update the caption (changes has been made in the original doc)
* Under the section: DIFFERENTIAL - PRIVACY IN REAL WORLD, just add "OpenDp by Harvard University and Microsoft "

Rest looks good, feel free to make any changes in the layout as per your choice.

2020-08-27 11:57 UTC, TravellerOnCode commented on docs/introduction.rst
> +    < a click from Secure AI Course>
Image Credits: Secure and Private AI (Udacity)

2020-08-27 11:58 UTC, TravellerOnCode commented on docs/introduction.rst
> +    (from google images)
Image Credits: Google Images

2020-08-27 11:59 UTC, TravellerOnCode commented on docs/introduction.rst
> +* `OpenDp  <https://github.com/opendifferentialprivacy>`_ by Harvard University
OpenDp by Harvard University and Microsoft

2020-08-27 12:02 UTC, TravellerOnCode commented on docs/introduction.rst
> +    :align: center
add the caption:
(Privacy Preserving AI by Andrew Trask | MIT Deep Learning Series )

2020-08-27 12:02 UTC, TravellerOnCode requested changes
Suggested Changes:

* Update the caption for the Images
* Under the section: DIFFERENTIAL - PRIVACY IN REAL WORLD, just add "OpenDp by Harvard University and Microsoft "

Rest looks good, feel free to make any changes in the layout as per your choice.

2020-08-28 18:12 UTC, 8bitmp3 commented
Awesome PR @shivaylamba! Are you open to edits to the text? There are a few things that stand out that could be polished.

2020-08-28 18:21 UTC, chinmayshah99 commented
@8bitmp3 please go ahead with the suggestions!

2020-08-28 23:53 UTC, shivaylamba commented
> Awesome PR @shivaylamba! Are you open to edits to the text? There are a few things that stand out that could be polished.

Yes @8bitmp3 Please let me know regarding any changes that I should make!

2020-08-29 00:02 UTC, shivaylamba commented
@TravellerOnCode I have made the suggested changes. Also I tried to centrally align the images but it always defaults to aligning to the left. I had a look at this open issue from 7 years back : https://github.com/github/markup/issues/163

2020-08-29 11:38 UTC, chinmayshah99 approved these changes

2020-08-29 11:38 UTC, merged

2020-09-04 17:04 UTC, chinmayshah99 commented
Fixes #207