commit
OpenMined/PyDP pull request #321
Opened 2020-10-31 15:16 UTC by festusdrakon

2020-11-01 17:52 UTC, chinmayshah99 commented
Can you fix the cpp style issues by running `make format-style-cpp`.

Also, can you change the PR title to be more descriptive?

2020-11-02 18:32 UTC, festusdrakon commented
Edited the PR title to make it more descriptive and executed  `make format-style-cpp`  to rectify styling errors.

2020-11-04 20:46 UTC, chinmayshah99 approved these changes

2020-11-08 13:14 UTC, alejandrosame approved these changes
LGTM

2020-11-08 15:09 UTC, shaistha24 commented
Hi @festusdrakon suggestion - along with the description could you also add the fields or attributes needed for each and give a short intro of it too. Adding the direct link  to the source code is also great. Makes it easier for the new contributors to look it up on the source code. 

You may use this as an example- https://www.tensorflow.org/api_docs/python/tf/config/LogicalDevice

Other than that nice work @festusdrakon

2020-11-08 15:24 UTC, shaistha24 requested changes
Hi @festusdrakon   along with the description could you also add the fields or attributes needed for each and give a short intro of it too. Adding the direct link to the source code is also great. Makes it easier for the new contributors to look it up on the source code.

You may use this as an example- https://www.tensorflow.org/api_docs/python/tf/config/LogicalDevice

Other than that nice work @festusdrakon

2020-11-08 15:24 UTC, shaistha24 commented on src/bindings/PyDP/algorithms/util.cpp
> +  m.def(
pls check my previous comment with the improvisations to be included.

2020-11-08 22:58 UTC, alejandrosame commented
@festusdrakon  The failed test is still running against pipenv version of dev branch. In order to make github realise that the target branch has changed before rerunning the tests you can do one of the following:

- Pull the latest dev changes to your fork, merge them to your brannch and push the merged changes.

- Momentarily change the target branch to a different one, save and then change it back to dev (see https://stackoverflow.com/a/26986320).

Let me know if you need further clarification or guidance. While I think the first solution is the cleanest, I understand that the second one is just fast and straightforward :)

2020-11-20 05:17 UTC, chinmayshah99 commented
@festusdrakon can you please pull the latest changes from dev as @alejandrosame suggested?

2021-01-18 06:50 UTC, chinmayshah99 commented
#341 fixes this.

2021-01-18 06:50 UTC, closed without merging