Checks for all notebooks
OpenMined/PyDP pull request #357
Opened 2021-04-21 12:32 UTC by dnabanita7

## Description
I have added ``pycodestyle``, ``flake8``, ``black``, ``mypy`` checks for all notebooks. #317 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2021-04-21 12:39 UTC, chinmayshah99 requested changes
I think `black` and `mypy` should suffice. Since these are the only two style tests we are using. Can you please make that change?

2021-04-21 13:26 UTC, chinmayshah99 approved these changes

2021-04-21 13:27 UTC, chinmayshah99 requested changes
can you please run black on this fork and update this to the latest version of dev?

2021-04-23 04:24 UTC, dnabanita7 commented
I guess its good to go @chinmayshah99

2021-04-25 08:58 UTC, chinmayshah99 approved these changes

2021-04-25 08:58 UTC, merged